# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DressUp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DressUp

  target 'DressUp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DressUpTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'DressUp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DressUp-tvOS

  target 'DressUp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
